# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0003_auto_20170119_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extention',
            field=models.IntegerField(choices=[(1, 'WebM Video File'), (2, 'MP4 Video File')], default=2),
            preserve_default=False,
        ),
    ]
